"""init_paper.py
====================
Refresh paper artifacts from a single source of truth (``paper/``)
into one of three output targets:

* ``--target paper``  (default) — refresh the original ``paper/``
  draft. Backward-compatible with previous invocations.
* ``--target iccas`` — emit a 1--2 page extended-abstract version into
  ``ICCAS/`` using the ICCAS 2026 class file.
* ``--target ijcas`` — emit a 6+ page full journal version into
  ``IJCAS/`` using the IJCAS class file.
* ``--target both`` — emit both ICCAS/ and IJCAS/ in one invocation.

The same ``paper/abstract_<variant>.tex`` and ``paper/tex/*.tex``
files feed every target — see ``SUBMISSION_PLAN.md`` for the dual
submission workflow.

Source files (single-source-of-truth in ``paper/``)
---------------------------------------------------
* ``abstract_completeness.tex`` / ``abstract_verifier.tex`` — abstract
  body, two variants. Picked by ``--variant``.
* ``tex/title_abstract.tex`` — author/title/affils/keywords metadata.
  Parsed with a brace-balanced extractor so it is robust to the
  ``\\abstract{...}`` body containing math braces.
* ``tex/intro_related.tex`` — full intro + related work (IJCAS only).
* ``tex/method.tex`` — full method (IJCAS only).
* ``tex/experiment.tex`` — full experiments (IJCAS only; regenerated).
* ``tex/conclusion.tex`` — IJCAS conclusion.
* ``tex/declarations.tex`` — IJCAS declarations.
* ``tex/biography.tex`` — IJCAS author bios.
* ``tex/short_body.tex`` — condensed intro + method + exp for ICCAS.
* ``literature_survey.md`` — reference list source.

Generated outputs (per target)
------------------------------
``paper/``  (target=paper)
  * ``tex/title_abstract.tex`` — abstract body refreshed in place.
  * ``tex/experiment.tex`` — refreshed from internal template.
  * ``references.bib``       — regenerated from literature_survey.md.
  * ``main.tex``             — inline ``thebibliography`` regenerated.
  * ``figures/``, ``tables/``— symlinked to latest run / generated.

``ICCAS/`` (target=iccas)
  * ``main.tex``             — rewritten (ICCAS class, condensed).
  * ``tex/title_abstract.tex`` — ICCAS-style command form.
  * ``tex/short_body.tex``   — copy of paper/tex/short_body.tex.
  * ``references.bib``       — copy of paper/references.bib.
  * ``figs/``, ``tables/``   — symlinked.

``IJCAS/`` (target=ijcas)
  * ``main.tex``             — rewritten (IJCAS class, full body).
  * ``tex/title_abstract.tex`` — IJCAS env form.
  * ``tex/intro_related.tex``, ``method.tex``, ``experiment.tex``,
    ``conclusion.tex``, ``declarations.tex``, ``biography.tex``
    — copies of paper/tex/* (figure paths rewritten figs/).
  * ``references.bib``       — copy of paper/references.bib.
  * ``figs/``, ``tables/``   — symlinked.

Usage
-----
    # Refresh the existing paper/ draft (backward-compat default):
    python scripts/init_paper.py
    python scripts/init_paper.py --variant verifier
    python scripts/init_paper.py --run-id 20260519_143552_c7c7ec

    # Emit the ICCAS 2026 short version:
    python scripts/init_paper.py --target iccas

    # Emit the IJCAS Special-Issue full version:
    python scripts/init_paper.py --target ijcas

    # Emit both at once (typical pre-submission):
    python scripts/init_paper.py --target both

    # See what would happen, write nothing:
    python scripts/init_paper.py --target both --dry-run
"""
from __future__ import annotations

import argparse
import os
import re
import shutil
import sys
import time
from typing import Iterable

_HERE       = os.path.dirname(os.path.abspath(__file__))
_PAPER_ROOT = os.path.abspath(os.path.join(_HERE, ".."))
_PAPER_DIR  = os.path.join(_PAPER_ROOT, "paper")
_ICCAS_DIR  = os.path.join(_PAPER_ROOT, "ICCAS")
_IJCAS_DIR  = os.path.join(_PAPER_ROOT, "IJCAS")
_FIG_ROOT   = os.path.join(_PAPER_ROOT, "figures")
_RESULTS    = os.path.join(_PAPER_ROOT, "results")
_GENERATED  = os.path.join(_PAPER_DIR, "generated")

# Marker comments. Used by the paper/ target's in-place edits.
_BEGIN = "% BEGIN AUTO-GENERATED by init_paper.py — do not hand-edit"
_END   = "% END AUTO-GENERATED"

# Default metadata used as a fallback if parsing title_abstract.tex fails.
_DEFAULT_TITLE = (
    r"SAGE: Lightweight Symbolic Verification and "
    r"Local Repair for LLM Task Planning in Embodied Agents"
)
_DEFAULT_AUTHORS = (
    r"Trung Minh Bui${}^{1}$, Jongsul Moon${}^{1}$, "
    r"YoungOuk Kim${}^{1}$, and Dongin Shin${}^{1,2*}$"
)
_DEFAULT_AFFILS = (
    "${}^{1}$Intelligent Robotics Research Center, "
    "Korea Electronics Technology Institute, \\\\\n"
    "Seongnam 13449, Republic of Korea \\\\\n"
    "(e-mails: \\{moonjongsul, kimyo\\}@keti.re.kr) \\\\\n"
    "${}^{2}$Department of Electronics Engineering, "
    "Kyung Hee University, \\\\\n"
    "Yongin 17104, Republic of Korea "
    "(e-mail: di\\_shin@keti.re.kr) "
    "{\\small${}^{*}$ Corresponding author}"
)
_DEFAULT_KEYWORDS = (
    "LLM task planning, embodied agents, symbolic verification, "
    "hierarchical planning, AI2-THOR."
)


# ─────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────
def _ts() -> str:
    return time.strftime("%Y%m%d_%H%M%S")


def _backup_once(path: str) -> str | None:
    if not os.path.exists(path):
        return None
    bk = f"{path}.bak.init_paper"
    if not os.path.exists(bk):
        shutil.copy2(path, bk)
        return bk
    return None


def _read(path: str) -> str:
    with open(path, "r", encoding="utf-8") as f:
        return f.read()


def _write(path: str, content: str, dry_run: bool) -> None:
    if dry_run:
        print(f"  [dry-run] would write {path} ({len(content)} bytes)")
        return
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)


def _replace_between(src: str, open_pat: str, close_pat: str, new_inner: str) -> str | None:
    m = re.search(rf"({open_pat})([\s\S]*?)({close_pat})", src)
    if not m:
        return None
    return src[: m.start(2)] + new_inner + src[m.end(2) :]


def _balanced_braces(text: str, start_idx: int) -> int:
    """Given an index pointing AT the opening '{', return the index of the
    matching closing '}' (i.e. so text[start_idx+1:return_idx] is the body).
    Returns -1 if no match. Treats backslash-escapes (``\\{``, ``\\}``) as
    literal characters."""
    if start_idx >= len(text) or text[start_idx] != "{":
        return -1
    depth = 0
    i = start_idx
    while i < len(text):
        c = text[i]
        if c == "\\" and i + 1 < len(text):
            i += 2
            continue
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                return i
        i += 1
    return -1


def _extract_command_arg(text: str, cmd: str) -> str | None:
    """Return the body of the FIRST occurrence of ``\\cmd{...}``, using
    brace-balanced matching so the body itself can contain ``{...}``."""
    # \cmd, optional whitespace, then `{`. Stop at first match.
    m = re.search(rf"\\{re.escape(cmd)}\s*\{{", text)
    if not m:
        return None
    open_idx = m.end() - 1   # index of the `{`
    close_idx = _balanced_braces(text, open_idx)
    if close_idx < 0:
        return None
    return text[open_idx + 1 : close_idx].strip()


# ─────────────────────────────────────────────────────────────────────
# Source-of-truth readers (paper/)
# ─────────────────────────────────────────────────────────────────────
def _read_clean_abstract(variant: str) -> str:
    """Return the abstract body from paper/abstract_<variant>.tex, with
    surrounding ``\\begin{abstract}`` / ``\\end{abstract}`` removed."""
    path = os.path.join(_PAPER_DIR, f"abstract_{variant}.tex")
    if not os.path.exists(path):
        raise SystemExit(f"variant source not found: {path}")
    text = _read(path)
    m = re.search(r"\\begin\{abstract\}\s*([\s\S]*?)\s*\\end\{abstract\}", text)
    if m:
        return m.group(1).strip()
    m = re.search(r"\\abstract\s*\{", text)
    if m:
        close = _balanced_braces(text, m.end() - 1)
        if close > 0:
            return text[m.end():close].strip()
    raise SystemExit(f"could not find abstract block in {path}")


def _read_metadata() -> dict:
    """Parse title / authors / affils / keywords out of paper/tex/title_abstract.tex.
    Uses brace-balanced extraction so the (possibly corrupted) ``\\abstract{...}``
    body does not confuse the parser. Falls back to defaults if a field is
    missing or empty."""
    path = os.path.join(_PAPER_DIR, "tex", "title_abstract.tex")
    if not os.path.exists(path):
        return dict(title=_DEFAULT_TITLE, authors=_DEFAULT_AUTHORS,
                    affils=_DEFAULT_AFFILS, keywords=_DEFAULT_KEYWORDS)
    src = _read(path)

    def _arg_or_default(cmd: str, default: str) -> str:
        v = _extract_command_arg(src, cmd)
        if v is None or not v.strip():
            return default
        return v.strip()

    return dict(
        title    = _arg_or_default("title",    _DEFAULT_TITLE),
        authors  = _arg_or_default("author",   _DEFAULT_AUTHORS),
        affils   = _arg_or_default("affils",   _DEFAULT_AFFILS),
        keywords = _arg_or_default("keywords", _DEFAULT_KEYWORDS),
    )


# ─────────────────────────────────────────────────────────────────────
# Target=paper — existing behaviour, kept for backward compatibility
# ─────────────────────────────────────────────────────────────────────
def _extract_abstract_body(tex_path: str) -> str:
    text = _read(tex_path)
    m = re.search(r"\\begin\{abstract\}\s*([\s\S]*?)\s*\\end\{abstract\}", text)
    if m:
        return m.group(1).strip()
    m = re.search(r"\\abstract\s*\{\s*([\s\S]+?)\s*\}\s*\Z", text)
    if m:
        return m.group(1).strip()
    raise SystemExit(
        f"could not find an abstract block in {tex_path} — "
        "expected either \\begin{abstract}...\\end{abstract} or \\abstract{...}"
    )


def update_title_abstract(variant: str, dry_run: bool) -> None:
    src_path = os.path.join(_PAPER_DIR, f"abstract_{variant}.tex")
    if not os.path.exists(src_path):
        raise SystemExit(f"variant source not found: {src_path}")
    dst_path = os.path.join(_PAPER_DIR, "tex", "title_abstract.tex")
    if not os.path.exists(dst_path):
        raise SystemExit(f"target not found: {dst_path}")

    abstract_body = _extract_abstract_body(src_path)
    dst = _read(dst_path)

    # Brace-balanced replacement of \abstract{...}.
    m = re.search(r"\\abstract\s*\{", dst)
    if not m:
        raise SystemExit(f"no \\abstract{{...}} block in {dst_path}")
    open_idx = m.end() - 1
    close_idx = _balanced_braces(dst, open_idx)
    if close_idx < 0:
        raise SystemExit(f"unbalanced \\abstract{{...}} in {dst_path}")
    new = dst[: open_idx + 1] + "\n" + abstract_body + "\n" + dst[close_idx:]
    if new == dst:
        print(f"  ✓ title_abstract.tex already current (variant={variant})")
        return
    _backup_once(dst_path)
    _write(dst_path, new, dry_run)
    print(f"  ✓ title_abstract.tex updated (variant={variant}, "
          f"{len(abstract_body)} char abstract)")


_EXPERIMENT_TEMPLATE = r"""% paper/tex/experiment.tex
% Auto-refreshed by scripts/init_paper.py. Hand-edit the prose; placeholder
% tables and figures are wired via \input{} so re-running gen_latex_table.py
% refreshes them without touching this file.

\section{Experiments}\label{sec:experiments}

We test three claims. (C1) SAGE attains the highest \emph{goal
completeness} on the AI2-THOR household benchmark across three
open-weight LLMs. (C2) Each of SAGE's three components --- the
symbolic verifier, the local repair operator, and the hybrid memory
store --- contributes a distinct, measurable improvement. (C3)
SAGE's plans satisfy a \emph{strict} precondition check that
exposes baselines as silently invalid even when their heuristic
precondition score is~$1.0$.

\subsection{Setup}\label{sec:setup}

\paragraph{Benchmark.}
We use the 38-task AI2-THOR household evaluation set distributed with
pyplanner (\texttt{eval\_dataset\_gt.json}). Tasks span kitchen
($K$, 9 tasks), living room ($L$, 8), bedroom ($B$, 8), bathroom
($A$, 8), and mixed-room scenarios ($X$, 5), with three difficulty
tiers. Every task has a simulator-verified reference plan used to
compute the step-ratio metric.

\paragraph{Evaluation modes.}
We run all sweeps in \emph{plan-quality mode} (offline, no
simulator). Selected runs are repeated in \emph{execution mode} using
AI2-THOR via the \texttt{thor\_server} client distributed with
pyplanner. Plan-quality mode is used for sweeps and ablations because
it eliminates simulator-side noise; execution mode is used for the
final task-success table.

\paragraph{Models.}
We benchmark across three open-weight Ollama models: \texttt{llama3.2}
(3B), \texttt{qwen2.5:7b}, and \texttt{mistral-nemo} (12B). All models
are accessed through the same backend (\texttt{LLMBackend} in
\texttt{pyplanner.base}); only the model identifier differs.

\paragraph{Baselines.}
We compare against the eight planning strategies registered in
\texttt{pyplanner.REGISTRY}: \texttt{Direct}, \texttt{CoT},
\texttt{Few-Shot CoT}~\cite{wei2022cot},
\texttt{Self-Refine}~\cite{madaan2023selfrefine},
\texttt{ReAct}~\cite{yao2022react}, \texttt{Hierarchical},
\texttt{LLM Router}, and \texttt{Hierarchical Few-Shot}. All share
the prompt scaffolding (action vocabulary, JSON schema), so
differences attribute to the planning strategy rather than prompt
engineering.

\paragraph{Metrics.}
For each (model, method, task) we record:
\begin{itemize}
  \item \textbf{Quality (higher is better):} \texttt{executability},
    \texttt{precondition} (heuristic), \texttt{precondition\_strict}
    (symbolic verifier), \texttt{completeness}.
  \item \textbf{Plan economy (lower is better):} \texttt{step\_ratio}
    ($|\pi| / |\pi^{\mathrm{ref}}|$), \texttt{redundancy},
    \texttt{hallucination}.
  \item \textbf{Cost (lower is better):} \texttt{llm\_calls},
    \texttt{total\_tokens}, \texttt{latency\_s}.
  \item \textbf{Execution (higher is better, sim mode):}
    \texttt{task\_success}, \texttt{step\_success\_rate},
    \texttt{total\_reward}.
\end{itemize}

\subsection{Main results --- plan quality}\label{sec:main}

%%% TABLE_MAIN %%%

The cost--quality trade-off is visualised in
Figure~\ref{fig:pareto}. SAGE consumes more tokens than one-shot
baselines but is the only method that simultaneously maintains a high
\texttt{completeness} score and a high
\texttt{precondition\_strict} score; baselines that match SAGE on
\texttt{completeness} fail the strict precondition check, and
baselines that pass the strict check miss expected objects.

\begin{figure}[t]
  \centering
  \includegraphics[width=\columnwidth]{figures/cost_quality_pareto.pdf}
  \caption{Cost--quality Pareto across planning methods and models.}
  \label{fig:pareto}
\end{figure}

\subsection{Heuristic vs strict precondition}\label{sec:strict}

A widely-reported plan-quality metric checks only that each
interaction is preceded by some \texttt{Navigate} or \texttt{Find},
without enforcing object identity, holding state, or container open
order. We re-evaluate every plan with the SAGE verifier and report
the strict score alongside the heuristic in
Figure~\ref{fig:strict}. Baselines that look perfect under the
heuristic collapse under the strict check, while SAGE retains its
score by construction.

\begin{figure}[t]
  \centering
  \includegraphics[width=\columnwidth]{figures/precondition_strict_vs_heuristic_qwen2.5_7b.pdf}
  \caption{Heuristic vs strict precondition --- \texttt{qwen2.5:7b}.}
  \label{fig:strict}
\end{figure}

\subsection{Execution table (AI2-THOR)}\label{sec:exec}

%%% TABLE_SIM %%%

\subsection{Ablation}\label{sec:ablation}

We isolate the contribution of each SAGE component by disabling it
in turn: \texttt{SAGE-NoVerifier} (no symbolic gate),
\texttt{SAGE-NoRepair} (replan falls back to global, not local), and
\texttt{SAGE-NoMemory} (no few-shot retrieval). Results are in
Figure~\ref{fig:ablation}; the full numbers are in the appendix.

\begin{figure}[t]
  \centering
  \includegraphics[width=\columnwidth]{figures/ablation_qwen2.5_7b.pdf}
  \caption{SAGE ablation on \texttt{qwen2.5:7b}.}
  \label{fig:ablation}
\end{figure}

\subsection{Failure cases}\label{sec:failure}

We hand-label SAGE failures on the 38-task set into three
categories: (i) object-naming ambiguity (a synonym the verifier
cannot match), (ii) mis-decomposition (high-level LLM omits a
required sub-goal), and (iii) sub-goal-boundary mismatch (the failed
step actually serves a future sub-goal). Object-naming ambiguity
dominates and is orthogonal to the planning strategy.

\subsection{Discussion}\label{sec:discussion}

SAGE's contribution is a \emph{deterministic} verifier and a
\emph{localised} repair operator integrated with hybrid memory. The
verifier costs zero tokens and runs in $O(|\pi|)$, yet exposes
silent precondition violations that fool the heuristic metric. The
local repair operator keeps already-completed work intact, which the
ablation shows is essential to SAGE's token economy. The hybrid
memory store grows over time, giving SAGE a smooth cold-start to
long-running-deployment path that single-source few-shot baselines
do not offer.
"""


def _table_inputs(tables_root: str) -> tuple[str, str]:
    """Return the LaTeX snippets for the main + sim tables, lazily.
    ``tables_root`` is the directory the LaTeX ``\\input{tables/...}`` paths
    will resolve to relative to the main.tex file."""
    main = sim = ""
    main_path = os.path.join(tables_root, "table_main.tex")
    sim_path  = os.path.join(tables_root, "table_sim.tex")
    if os.path.exists(main_path):
        main = (
            "\\begin{table*}[t]\n"
            "\\centering\n"
            "\\caption{Mean plan-quality and cost per (model, method) over 38 tasks.}\n"
            "\\label{tab:main}\n"
            "\\input{tables/table_main}\n"
            "\\end{table*}"
        )
    else:
        main = (
            "% tables/table_main.tex not found — run:\n"
            "%   python scripts/gen_latex_table.py --table main \\\n"
            "%       --csv results/<run_id>/results.csv \\\n"
            "%       --out paper/generated/table_main.tex"
        )
    if os.path.exists(sim_path):
        sim = (
            "\\begin{table}[t]\n"
            "\\centering\n"
            "\\caption{AI2-THOR execution results --- \\texttt{qwen2.5:7b}.}\n"
            "\\label{tab:sim}\n"
            "\\input{tables/table_sim}\n"
            "\\end{table}"
        )
    else:
        sim = (
            "% tables/table_sim.tex not found — run:\n"
            "%   python scripts/gen_latex_table.py --table sim \\\n"
            "%       --csv results/<run_id>/sim_qwen2.5_7b.csv \\\n"
            "%       --out paper/generated/table_sim.tex"
        )
    return main, sim


def update_experiment_tex(dry_run: bool) -> None:
    main_snippet, sim_snippet = _table_inputs(_GENERATED)
    body = _EXPERIMENT_TEMPLATE
    body = body.replace("%%% TABLE_MAIN %%%", main_snippet)
    body = body.replace("%%% TABLE_SIM %%%",  sim_snippet)
    dst = os.path.join(_PAPER_DIR, "tex", "experiment.tex")
    if os.path.exists(dst) and _read(dst) == body:
        print("  ✓ experiment.tex already current")
        return
    _backup_once(dst)
    _write(dst, body, dry_run)
    print(f"  ✓ experiment.tex rewritten ({len(body)} bytes)")


# ─────────────────────────────────────────────────────────────────────
# References parsing — shared by all targets
# ─────────────────────────────────────────────────────────────────────
_VENUE_INPROC_ACRONYMS = [
    "NeurIPS", "ICML", "ICLR", "AAAI", "IJCAI", "ICCV", "CVPR", "ECCV",
    "ICRA", "IROS", "CoRL", "RSS", "ACL", "EMNLP", "NAACL", "AAMAS",
    "UIST", "CHI", "KDD", "SIGIR", "SIGCOMM",
]
_VENUE_JOURNAL_ACRONYMS = [
    "RA-L", "TPAMI", "TRO", "IJRR", "JAIR", "TAC", "TAES",
]
_VENUE_JOURNAL_PHRASES = [
    "international journal",
    "ieee robotics",
    "ieee transactions",
    "transactions on",
]


def _has_word(word: str, text: str, *, case_sensitive: bool) -> bool:
    flags = 0 if case_sensitive else re.IGNORECASE
    pat = rf"(?:^|[^A-Za-z0-9]){re.escape(word)}(?:$|[^A-Za-z0-9])"
    return bool(re.search(pat, text, flags))


def _bib_key(authors: str, year: str, title: str) -> str:
    surname = re.split(r"\s+", authors.strip())[0].lower()
    surname = re.sub(r"[^a-z]", "", surname)
    first_word = re.findall(r"[a-z]{3,}", title.lower())
    tag = first_word[0] if first_word else "ref"
    return f"{surname}{year}{tag}"


def _infer_type(description: str) -> str:
    for v in _VENUE_INPROC_ACRONYMS:
        if _has_word(v, description, case_sensitive=True):
            return "inproceedings"
    for v in _VENUE_JOURNAL_ACRONYMS:
        if _has_word(v, description, case_sensitive=True):
            return "article"
    for v in _VENUE_JOURNAL_PHRASES:
        if v in description.lower():
            return "article"
    return "misc"


def _venue_from_desc(description: str) -> str:
    for v in _VENUE_INPROC_ACRONYMS + _VENUE_JOURNAL_ACRONYMS:
        if _has_word(v, description, case_sensitive=True):
            return v
    if "arxiv" in description.lower():
        return "arXiv preprint"
    return ""


def _latex_escape(s: str) -> str:
    return (s.replace("\\", r"\textbackslash{}")
             .replace("&",  r"\&")
             .replace("%",  r"\%")
             .replace("$",  r"\$")
             .replace("#",  r"\#")
             .replace("_",  r"\_"))


def _bibtex_entry(etype: str, key: str, fields: dict) -> str:
    lines = [f"@{etype}{{{key},"]
    for k, v in fields.items():
        if not v:
            continue
        v_str = str(v).strip() if k == "url" else _latex_escape(str(v).strip())
        lines.append(f"  {k:9s} = {{{v_str}}},")
    lines[-1] = lines[-1].rstrip(",")
    lines.append("}")
    return "\n".join(lines)


def parse_survey(survey_path: str) -> list[dict]:
    text = _read(survey_path)
    pat = re.compile(
        r"\*\*([^*]+?)\s*\(([^)]+?)(?:,\s*|\s+)(\d{4})\)"
        r"\.?\*\*\s*(?:[—–-]+\s*)?"
        r"([\s\S]*?)"
        r"URL[s]?:\s*(\S+)",
        re.MULTILINE,
    )
    out = []
    for m in pat.finditer(text):
        title    = m.group(1).strip().rstrip(".,")
        authors  = m.group(2).strip().rstrip(",")
        year     = m.group(3).strip()
        descr    = m.group(4).strip()
        url      = m.group(5).strip().rstrip(".,")
        out.append({
            "title":   title,
            "authors": authors,
            "year":    year,
            "descr":   descr,
            "url":     url,
        })
    return out


def _entries_from_survey() -> list[dict]:
    """Parse literature_survey.md and add per-entry derived fields needed
    by the bibitem renderer. Returns the structured list."""
    survey = os.path.join(_PAPER_DIR, "literature_survey.md")
    if not os.path.exists(survey):
        return []
    entries = parse_survey(survey)
    structured: list[dict] = []
    seen: set[str] = set()
    for e in entries:
        key = _bib_key(e["authors"], e["year"], e["title"])
        base = key
        i = 1
        while key in seen:
            i += 1
            key = f"{base}{chr(ord('a') + i - 1)}"
        seen.add(key)
        composite = e["authors"] + "\n" + e["descr"]
        etype = _infer_type(composite)
        venue = _venue_from_desc(composite)
        authors = e["authors"]
        authors_bib = re.sub(r"\bet al\.?", "and others", authors)
        authors_bib = re.split(r",\s*(?:Google|NVIDIA|UT Austin|OpenAI|Anthropic|"
                               r"Meta|DeepMind|MSR|Microsoft|Stanford)\b",
                               authors_bib)[0]
        structured.append({**e, "key": key, "etype": etype, "venue": venue,
                           "authors_bib": authors_bib})
    return structured


def generate_references_bib(target_dir: str, entries: list[dict],
                            dry_run: bool) -> None:
    """Write references.bib to ``target_dir``. ``entries`` is the list
    returned by ``_entries_from_survey()``."""
    if not entries:
        print(f"  [skip] no survey entries — references.bib not written to {target_dir}")
        return
    bib_chunks: list[str] = [
        f"% {os.path.basename(target_dir)}/references.bib",
        "% Auto-generated by scripts/init_paper.py from paper/literature_survey.md.",
        "% To regenerate: python scripts/init_paper.py --target <paper|iccas|ijcas|both>",
        "",
    ]
    for e in entries:
        curated = _CURATED_REFS.get(e["key"], {})
        etype = curated.get("etype") or e["etype"]
        fields = {
            "title":  curated.get("title")   or e["title"],
            "author": curated.get("authors") or e["authors_bib"],
            "year":   curated.get("year")    or e["year"],
            "url":    e["url"],
        }
        venue = curated.get("venue") or e["venue"]
        if etype == "inproceedings":
            fields["booktitle"] = venue or "Proc. of the Conference"
        elif etype == "article":
            fields["journal"] = venue or "Journal"
        bib_chunks.append(_bibtex_entry(etype, e["key"], fields))
        bib_chunks.append("")
    bib_text = "\n".join(bib_chunks).rstrip() + "\n"
    dst = os.path.join(target_dir, "references.bib")
    if os.path.exists(dst) and _read(dst) == bib_text:
        print(f"  ✓ {dst} already current ({len(entries)} entries)")
        return
    _backup_once(dst)
    _write(dst, bib_text, dry_run)
    print(f"  ✓ {dst} written ({len(entries)} entries)")


# Curated full bibliographic info for the keys this paper cites.
# The literature_survey.md uses short conceptual names (``SayCan'',
# ``Inner Monologue'') which read as placeholders in the rendered
# bibliography. This table substitutes the verified full title and venue
# so the rendered \bibitem is a complete reference. Keys not in this
# table fall back to the survey-derived rendering.
_CURATED_REFS = {
    "ahn2022saycan": dict(
        title="Do as I can, not as I say: Grounding language in robotic affordances",
        authors="M. Ahn et al.", venue="CoRL", year="2022",
        etype="inproceedings"),
    "huang2022inner": dict(
        title="Inner Monologue: Embodied reasoning through planning with language models",
        authors="W. Huang et al.", venue="CoRL", year="2022",
        etype="inproceedings"),
    "singh2022progprompt": dict(
        title="ProgPrompt: Generating situated robot task plans using large language models",
        authors="I. Singh et al.", venue="ICRA", year="2023",
        etype="inproceedings"),
    "liang2022code": dict(
        title="Code as Policies: Language model programs for embodied control",
        authors="J. Liang et al.", venue="ICRA", year="2023",
        etype="inproceedings"),
    "liu2023llm": dict(
        title="LLM+P: Empowering large language models with optimal planning proficiency",
        authors="B. Liu et al.", year="2023"),
    "dagan2023llm": dict(
        title="Dynamic planning with a LLM",
        authors="G. Dagan, F. Keller, and A. Lascarides", year="2023"),
    "wei2022chain": dict(
        title="Chain-of-Thought prompting elicits reasoning in large language models",
        authors="J. Wei et al.", venue="NeurIPS", year="2022",
        etype="inproceedings"),
    "yao2022react": dict(
        title="ReAct: Synergizing reasoning and acting in language models",
        authors="S. Yao et al.", venue="ICLR", year="2023",
        etype="inproceedings"),
    "shinn2023reflexion": dict(
        title="Reflexion: Language agents with verbal reinforcement learning",
        authors="N. Shinn et al.", venue="NeurIPS", year="2023",
        etype="inproceedings"),
    "madaan2023self": dict(
        title="Self-Refine: Iterative refinement with self-feedback",
        authors="A. Madaan et al.", venue="NeurIPS", year="2023",
        etype="inproceedings"),
    "yao2023tree": dict(
        title="Tree of Thoughts: Deliberate problem solving with large language models",
        authors="S. Yao et al.", venue="NeurIPS", year="2023",
        etype="inproceedings"),
    "song2023llm": dict(
        title="LLM-Planner: Few-shot grounded planning for embodied agents with large language models",
        authors="C. H. Song et al.", venue="ICCV", year="2023",
        etype="inproceedings"),
    "zhou2024isr": dict(
        title="ISR-LLM: Iterative self-refined large language model for long-horizon sequential task planning",
        authors="Z. Zhou et al.", venue="ICRA", year="2024",
        etype="inproceedings"),
    "icml2024kambhampati": dict(
        title="LLMs can't plan, but can help planning in LLM-Modulo frameworks",
        authors="S. Kambhampati et al.", venue="ICML", year="2024",
        etype="inproceedings"),
    "kolve2020thor": dict(
        title="AI2-THOR: An interactive 3D environment for visual AI",
        authors="E. Kolve et al.", year="2017"),
    "shridhar2021alfworld": dict(
        title="ALFWorld: Aligning text and embodied environments for interactive learning",
        authors="M. Shridhar et al.", venue="ICLR", year="2021",
        etype="inproceedings"),
    "ajay2023hip": dict(
        title="Compositional foundation models for hierarchical planning",
        authors="A. Ajay et al.", venue="NeurIPS", year="2023",
        etype="inproceedings"),
    "fu2024autoguide": dict(
        title="AutoGuide: Automated generation and selection of context-aware guidelines for large language model agents",
        authors="Y. Fu et al.", venue="NeurIPS", year="2024",
        etype="inproceedings"),
    "zhao2024expel": dict(
        title="ExpeL: LLM agents are experiential learners",
        authors="A. Zhao et al.", venue="AAAI", year="2024",
        etype="inproceedings"),
    "wang2023voyager": dict(
        title="Voyager: An open-ended embodied agent with large language models",
        authors="G. Wang et al.", year="2023"),
    "wang2023deps": dict(
        title="Describe, Explain, Plan and Select: Interactive planning with large language models enables open-world multi-task agents",
        authors="Z. Wang et al.", venue="NeurIPS", year="2023",
        etype="inproceedings"),
    "sun2023adaplanner": dict(
        title="AdaPlanner: Adaptive planning from feedback with language models",
        authors="H. Sun et al.", venue="NeurIPS", year="2023",
        etype="inproceedings"),
    "mei2024replanvlm": dict(
        title="ReplanVLM: Replanning robotic tasks with visual language models",
        authors="A. Mei et al.", year="2024"),
    "lin2023swiftsage": dict(
        title="SwiftSage: A generative agent with fast and slow thinking for complex interactive tasks",
        authors="B. Y. Lin et al.", venue="NeurIPS", year="2023",
        etype="inproceedings"),
    "neurips2023guan": dict(
        title="Leveraging pre-trained large language models to construct and utilize world models for model-based task planning",
        authors="L. Guan et al.", venue="NeurIPS", year="2023",
        etype="inproceedings"),
    "hao2023rap": dict(
        title="Reasoning with language model is planning with world model",
        authors="S. Hao et al.", venue="EMNLP", year="2023",
        etype="inproceedings"),
    # Concurrent / recent (2024--2025) — keep narrative current.
    "bian2025llm": dict(
        title="Large language model-based task planning for service robots: A review",
        authors="S. Bian, Y. Zhang, G. Tian, et al.",
        year="2025"),
    "ma2025self": dict(
        title="S\\textsuperscript{2}R: Teaching LLMs to self-verify and self-correct via reinforcement learning",
        authors="R. Ma, P. Wang, C. Liu, et al.",
        year="2025"),
    "verma2025pddl": dict(
        title="PDDL-Instruct: Teaching LLMs to plan via logical chain-of-thought instruction tuning",
        authors="P. Verma, N. La, A. Favier, et al.",
        year="2025"),
    "jang2024foundation": dict(
        title="Unlocking robotic autonomy: A survey on the applications of foundation models",
        authors="D.-S. Jang, D.-H. Cho, W.-C. Lee, et al.",
        venue="International Journal of Control, Automation, and Systems",
        year="2024", etype="article"),
    "hwang2024safe": dict(
        title="Safe motion planning and control for mobile robots: A survey",
        authors="S. Hwang, I. Jang, D. Kim, et al.",
        venue="International Journal of Control, Automation, and Systems",
        year="2024", etype="article"),
}


def _arxiv_id(url: str) -> str:
    """Extract the arXiv ID from a URL like https://arxiv.org/abs/2204.01691.
    Returns an empty string if the URL is not an arXiv URL."""
    m = re.search(r"arxiv\.org/(?:abs|pdf)/(\d{4}\.\d{4,5})", url or "")
    return m.group(1) if m else ""


def _format_authors_for_display(raw: str) -> str:
    """Convert 'Ahn and others' / 'Ahn et al' into 'Ahn et al.' for the
    rendered bibitem; multi-author lists are kept verbatim."""
    s = re.sub(r"\band others\b", "et al.", raw).strip()
    if not s.endswith(".") and s.lower().endswith("et al"):
        s += "."
    return s


def _bibitem_line(entry: dict) -> str:
    """Render one ``\\bibitem{key}`` block for a thebibliography list.

    The rendered entry includes (when available):
      - Authors with ``et al.`` rather than ``and others`` for IEEE style.
      - Real arXiv identifier (``arXiv:2204.01691``) parsed from the URL,
        so the reference is verifiable by ID and not just an URL.
      - Venue when known (inproceedings/article); falls back to
        ``arXiv preprint arXiv:NNNN.NNNNN`` for unpublished preprints.
    """
    key     = entry["key"]
    curated = _CURATED_REFS.get(key, {})
    title   = _latex_escape(curated.get("title") or entry["title"])
    authors = _latex_escape(curated.get("authors")
                            or _format_authors_for_display(entry["authors_bib"]))
    year    = curated.get("year")  or entry["year"]
    venue   = curated.get("venue") or entry["venue"] or ""
    etype   = curated.get("etype") or entry["etype"]
    arxiv   = _arxiv_id(entry.get("url", ""))
    if etype == "inproceedings":
        venue_str = (f"in \\textit{{Proc. of {venue}}}, "
                     if venue else "in \\textit{Proc. of the Conference}, ")
        body = f"{authors}, ``{title},'' {venue_str}{year}."
    elif etype == "article":
        venue_str = f"\\textit{{{venue}}}, " if venue else ""
        body = f"{authors}, ``{title},'' {venue_str}{year}."
    else:
        if arxiv:
            preprint_tag = f"arXiv preprint arXiv:{arxiv}"
        else:
            preprint_tag = venue or "arXiv preprint"
        body = f"{authors}, ``{title},'' {preprint_tag}, {year}."
    return f"\\bibitem{{{key}}}\n{body}"


def _bibliography_block(entries: list[dict]) -> str:
    """Return a full ``\\begin{thebibliography}{99} ... \\end{thebibliography}``
    block (including the begin/end lines)."""
    lines = [
        r"\begin{thebibliography}{99}",
        "% --- references --- regenerated by scripts/init_paper.py ---",
        "% To switch to BibTeX, replace this block with:",
        r"%     \bibliographystyle{IEEEtran}",
        r"%     \bibliography{references}",
        "% and run: pdflatex main && bibtex main && pdflatex main && pdflatex main",
        "",
    ]
    for e in entries:
        lines.append(_bibitem_line(e))
        lines.append("")
    lines.append(r"\end{thebibliography}")
    return "\n".join(lines).rstrip() + "\n"


def update_main_bibliography(entries: list[dict], dry_run: bool) -> None:
    """In-place edit of paper/main.tex bibliography block (target=paper)."""
    main = os.path.join(_PAPER_DIR, "main.tex")
    src = _read(main)
    block_lines = [
        "% --- references --- regenerated by scripts/init_paper.py ---",
        "% To switch to BibTeX, replace this block with:",
        "%     \\bibliographystyle{IEEEtran}",
        "%     \\bibliography{references}",
        "% and run: pdflatex main && bibtex main && pdflatex main && pdflatex main",
        "",
    ]
    for e in entries:
        block_lines.append(_bibitem_line(e))
        block_lines.append("")
    new_inner = "\n" + "\n".join(block_lines).rstrip() + "\n"
    new_src = _replace_between(
        src,
        r"\\begin\{thebibliography\}\{99\}",
        r"\\end\{thebibliography\}",
        new_inner,
    )
    if new_src is None:
        raise SystemExit("could not find thebibliography in paper/main.tex")
    if new_src == src:
        print("  ✓ main.tex bibliography already current")
        return
    _backup_once(main)
    _write(main, new_src, dry_run)
    print(f"  ✓ main.tex bibliography updated ({len(entries)} entries)")


# ─────────────────────────────────────────────────────────────────────
# Figures / tables symlink helpers — shared
# ─────────────────────────────────────────────────────────────────────
def _resolve_run(run_id: str) -> str:
    if run_id == "latest" or not run_id:
        candidates = sorted(
            (d for d in os.listdir(_FIG_ROOT) if os.path.isdir(os.path.join(_FIG_ROOT, d))),
            reverse=True,
        )
        if not candidates:
            raise SystemExit(f"no figure runs found in {_FIG_ROOT}")
        return candidates[0]
    if not os.path.isdir(os.path.join(_FIG_ROOT, run_id)):
        raise SystemExit(f"figure run not found: {os.path.join(_FIG_ROOT, run_id)}")
    return run_id


def _link_or_copy(src: str, dst: str) -> None:
    # Guard: src and dst resolve to the same real path. This happens when
    # the figures fallback aims paper/figures/ at itself for target=paper.
    # Replacing the file with a self-symlink would destroy it.
    try:
        if os.path.realpath(src) == os.path.realpath(dst):
            return
    except OSError:
        pass
    if os.path.islink(dst) or os.path.exists(dst):
        os.remove(dst)
    try:
        os.symlink(os.path.relpath(src, os.path.dirname(dst)), dst)
    except (OSError, NotImplementedError):
        shutil.copy2(src, dst)


def _link_figures_dir(run_id: str, dst_dir: str, dry_run: bool) -> None:
    """Populate ``dst_dir`` with .pdf and .eps files from
    ``figures/<run_id>/`` (symlinks where possible). Falls back to
    ``paper/figures/`` when no top-level figures/ tree exists yet."""
    if not os.path.isdir(_FIG_ROOT):
        fallback = os.path.join(_PAPER_DIR, "figures")
        if os.path.isdir(fallback):
            print(f"  [fallback] no figures/ root — sourcing from paper/figures/")
            src = fallback
            chosen = "paper/figures"
        else:
            print(f"  [skip] no figures/ root yet — run `make plots` first")
            return
    else:
        chosen = _resolve_run(run_id)
        src = os.path.join(_FIG_ROOT, chosen)
    # Same-dir guard: if src and dst are the same directory (the fallback
    # path with target=paper), nothing to do — the files are already there.
    if os.path.realpath(src) == os.path.realpath(dst_dir):
        print(f"  ✓ figures already in place at {dst_dir} (source = destination)")
        return
    print(f"  → figures source: {chosen}  →  {dst_dir}")
    if dry_run:
        n = sum(1 for f in os.listdir(src) if f.endswith((".pdf", ".eps")))
        print(f"  [dry-run] would link {n} .pdf/.eps files into {dst_dir}")
        return
    os.makedirs(dst_dir, exist_ok=True)
    n = 0
    for fn in sorted(os.listdir(src)):
        if not fn.endswith((".pdf", ".eps")):
            continue
        _link_or_copy(os.path.join(src, fn), os.path.join(dst_dir, fn))
        n += 1
    print(f"  ✓ {n} figure files linked into {dst_dir}")


def _link_tables_dir(dst_dir: str, dry_run: bool) -> None:
    """Symlink ``paper/generated/`` as ``<dst_dir>``. ``dst_dir`` is the
    target path (e.g. ``ICCAS/tables``); we replace the symlink/dir if
    one already exists."""
    if not os.path.isdir(_GENERATED):
        print(f"  [skip] paper/generated/ not found — generate tables first")
        return
    if dry_run:
        print(f"  [dry-run] would link {dst_dir} -> {_GENERATED}")
        return
    if os.path.islink(dst_dir) or os.path.exists(dst_dir):
        if os.path.islink(dst_dir):
            os.remove(dst_dir)
        else:
            shutil.rmtree(dst_dir)
    os.symlink(os.path.relpath(_GENERATED, os.path.dirname(dst_dir)), dst_dir)
    print(f"  ✓ tables symlink: {dst_dir} -> generated/")


def _link_portraits_dir(dst_dir: str, dry_run: bool) -> None:
    """Symlink ``paper/portraits/`` as ``<dst_dir>`` for IJCAS-style
    biographies. No-op if no portraits directory exists."""
    portraits_src = os.path.join(_PAPER_DIR, "portraits")
    if not os.path.isdir(portraits_src):
        print(f"  [skip] paper/portraits/ not found — biographies will use the placeholder image")
        return
    if dry_run:
        print(f"  [dry-run] would link {dst_dir} -> {portraits_src}")
        return
    if os.path.islink(dst_dir) or os.path.exists(dst_dir):
        if os.path.islink(dst_dir):
            os.remove(dst_dir)
        else:
            shutil.rmtree(dst_dir)
    os.symlink(os.path.relpath(portraits_src, os.path.dirname(dst_dir)),
               dst_dir)
    print(f"  ✓ portraits symlink: {dst_dir} -> {os.path.basename(portraits_src)}/")


def setup_figures(run_id: str, dry_run: bool) -> None:
    """Backward-compat wrapper: target=paper figures directory."""
    _link_figures_dir(run_id, os.path.join(_PAPER_DIR, "figures"), dry_run)


def setup_tables(dry_run: bool) -> None:
    """Backward-compat wrapper: target=paper tables symlink."""
    _link_tables_dir(os.path.join(_PAPER_DIR, "tables"), dry_run)


# ─────────────────────────────────────────────────────────────────────
# Path-rewriting helpers for emit_iccas / emit_ijcas
# ─────────────────────────────────────────────────────────────────────
def _rewrite_fig_paths(text: str, *, from_dir: str = "figures", to_dir: str = "figs") -> str:
    """Replace ``figures/`` with ``figs/`` (or whatever the venue uses)
    inside ``\\includegraphics{...}`` arguments. Conservative: only
    rewrites occurrences inside includegraphics."""
    def _rewrite(match: re.Match) -> str:
        opts = match.group(1) or ""
        path = match.group(2)
        new_path = re.sub(rf"\b{re.escape(from_dir)}/", f"{to_dir}/", path)
        return f"\\includegraphics{opts}{{{new_path}}}"
    return re.sub(r"\\includegraphics(\[[^\]]*\])?\{([^}]+)\}", _rewrite, text)


def _copy_with_rewrite(src: str, dst: str, dry_run: bool,
                       *, fig_dir: str = "figs") -> None:
    """Copy a .tex source file rewriting figure paths from ``figures/``
    to ``<fig_dir>/``."""
    if not os.path.exists(src):
        print(f"  [warn] missing source: {src}")
        return
    text = _read(src)
    new_text = _rewrite_fig_paths(text, from_dir="figures", to_dir=fig_dir)
    _write(dst, new_text, dry_run)
    rewrote = "" if new_text == text else "  (figure paths rewritten)"
    print(f"  ✓ {os.path.relpath(dst, _PAPER_ROOT)}{rewrote}")


# ─────────────────────────────────────────────────────────────────────
# Target=ICCAS — emit ICCAS/ artifacts
# ─────────────────────────────────────────────────────────────────────
_ICCAS_TITLE_ABSTRACT_TMPL = r"""% ICCAS/tex/title_abstract.tex
% AUTO-GENERATED by scripts/init_paper.py --target iccas. Re-running the
% script will overwrite this file. Hand-edit the source in paper/ instead.

\title{__TITLE__}

\author{__AUTHORS__}

\affils{__AFFILS__}


\abstract{
__ABSTRACT__
}

\keywords{
    __KEYWORDS__
}
"""

_ICCAS_MAIN_TMPL = r"""%% ICCAS 2026 — SAGE submission.
%% AUTO-GENERATED by scripts/init_paper.py --target iccas.
%% Hand-edit the source files in paper/ and re-run the script.

\documentclass[10pt,twocolumn]{ICCAS}

%%%%%%% set heading and page number here %%%%%%%%%%
% Do not put page numbers for submission.
%\setcounter{page}{101}

\usepackage{diagbox}
\usepackage{graphicx}
\usepackage{booktabs}
\usepackage{multirow}

\begin{document}

%\thanks{ \noindent
%   This paper is supported by my funding agencies.
%}

\input{tex/title_abstract}

\maketitle

\input{tex/short_body}

%%%%%%%%%%%%%%%%% BIBLIOGRAPHY %%%%%%%%%%%%%%%%%%
__BIBLIOGRAPHY__
%%--------------------------------------------------------------------%%

\end{document}
"""


def _cited_keys_in(*paths: str) -> set[str]:
    """Return the set of bib keys referenced via ``\\cite{...}`` in any
    of the given .tex files. Handles comma-separated key lists."""
    keys: set[str] = set()
    pat = re.compile(r"\\cite[a-z]*\{([^}]+)\}")
    for p in paths:
        if not os.path.exists(p):
            continue
        for m in pat.finditer(_read(p)):
            for k in m.group(1).split(","):
                k = k.strip()
                if k:
                    keys.add(k)
    return keys


def emit_iccas(variant: str, run_id: str, entries: list[dict],
               dry_run: bool) -> None:
    print(f"[ICCAS] variant={variant}, run-id={run_id}")
    meta = _read_metadata()
    abstract = _read_clean_abstract(variant)

    # 1. title_abstract.tex (command form)
    ta = _ICCAS_TITLE_ABSTRACT_TMPL
    ta = ta.replace("__TITLE__",    meta["title"])
    ta = ta.replace("__AUTHORS__",  meta["authors"])
    ta = ta.replace("__AFFILS__",   meta["affils"])
    ta = ta.replace("__ABSTRACT__", abstract)
    ta = ta.replace("__KEYWORDS__", meta["keywords"])
    _write(os.path.join(_ICCAS_DIR, "tex", "title_abstract.tex"), ta, dry_run)
    print(f"  ✓ ICCAS/tex/title_abstract.tex written ({len(abstract)} char abstract)")

    # 2. short_body.tex — copy from paper/
    short_src = os.path.join(_PAPER_DIR, "tex", "short_body.tex")
    if not os.path.exists(short_src):
        raise SystemExit(f"missing source: {short_src} — create it first")
    _copy_with_rewrite(short_src,
                       os.path.join(_ICCAS_DIR, "tex", "short_body.tex"),
                       dry_run, fig_dir="figs")

    # 3. main.tex — filter the bibliography to only entries cited in the
    #    ICCAS short body. The full survey lives unmodified in
    #    paper/literature_survey.md for the IJCAS journal version.
    cited = _cited_keys_in(short_src)
    iccas_entries = [e for e in entries if e["key"] in cited] if cited else entries
    print(f"  → bibliography filtered: {len(iccas_entries)}/{len(entries)} cited")
    bib_block = _bibliography_block(iccas_entries) if iccas_entries else \
                r"\begin{thebibliography}{99}" "\n" \
                "% no entries — populate paper/literature_survey.md\n" \
                r"\end{thebibliography}" "\n"
    main = _ICCAS_MAIN_TMPL.replace("__BIBLIOGRAPHY__", bib_block.rstrip())
    _write(os.path.join(_ICCAS_DIR, "main.tex"), main, dry_run)
    print(f"  ✓ ICCAS/main.tex written ({len(iccas_entries)} bib entries)")

    # 4. references.bib (for users who later switch to bibtex)
    generate_references_bib(_ICCAS_DIR, iccas_entries, dry_run)

    # 5. figures (figs/) and tables (tables/)
    _link_figures_dir(run_id, os.path.join(_ICCAS_DIR, "figs"), dry_run)
    _link_tables_dir(os.path.join(_ICCAS_DIR, "tables"), dry_run)


# ─────────────────────────────────────────────────────────────────────
# Target=IJCAS — emit IJCAS/ artifacts
# ─────────────────────────────────────────────────────────────────────
_IJCAS_TITLE_ABSTRACT_TMPL = r"""% IJCAS/tex/title_abstract.tex
% AUTO-GENERATED by scripts/init_paper.py --target ijcas. Re-running the
% script will overwrite this file. Hand-edit the source in paper/ instead.

\title{__TITLE__}

\author{__AUTHORS_PLAIN__}

\begin{abstract}
__ABSTRACT__
\end{abstract}

\begin{keywords}
    __KEYWORDS__
\end{keywords}

\maketitle

\makeAuthorInformation{
Manuscript received January 10, 2026; revised March 10, 2026;
accepted May 10, 2026.\\
%
__AFFILS_PLAIN__\\
* Corresponding author.
}

\runningtitle{__YEAR__}{__AUTHORS_PLAIN__}{__TITLE__}{xxx}{xxxx}{x}
"""

_IJCAS_MAIN_TMPL = r"""%% IJCAS Special Issue: ICCAS 2026 — SAGE submission.
%% AUTO-GENERATED by scripts/init_paper.py --target ijcas.
%% Hand-edit the source files in paper/ and re-run the script.

\documentclass{IJCAS}

%% LaTeX packages
\usepackage{url}
\usepackage{array,tabularx}
\usepackage{multicol}
\usepackage{fix-cm}
\usepackage{lmodern}
\usepackage{diagbox}
\usepackage{amsmath,amssymb,amsfonts}
\usepackage{algorithm}
\usepackage{algpseudocode}   % defines \State / \For / \If / \Return etc.
\usepackage{graphicx}
\usepackage{booktabs}
\usepackage{multirow}
\usepackage{xcolor}
\usepackage{cite}
\usepackage{subcaption}
\usepackage{bm}

%%%%%%%%%% equation center alignment
\usepackage{etoolbox}
\makeatletter
\AfterEndPreamble{%
  \@fleqnfalse
  \setlength{\mathindent}{0pt}%
}
\makeatother

%%%% Editorial Information — leave as placeholders for journal office.
\journalvolumn{VV}
\journalnumber{X}
\journalyear{__YEAR__}
\setarticlestartpagenumber{1}

\allowdisplaybreaks

\begin{document}

\input{tex/title_abstract}

\input{tex/intro_related}
\input{tex/method}
\input{tex/experiment}
\input{tex/conclusion}

\input{tex/acknowledgement}

%%%%%%%%%%%%%%%%% BIBLIOGRAPHY %%%%%%%%%%%%%%%%%%
__BIBLIOGRAPHY__

\input{tex/biography}

\end{document}
"""


def _plainify_authors(authors_tex: str) -> str:
    """Convert ICCAS-style ``First A. Author${}^{1}$ and ...`` into a plain
    string suitable for the IJCAS ``\\author{...}`` argument (which expects
    a comma- and ``and``-separated list without affiliation superscripts)."""
    txt = re.sub(r"\$\{?\}?\^\{[^{}]*\}\$", "", authors_tex)   # ${}^{1}$
    txt = re.sub(r"\$\^\{[^{}]*\}\$", "", txt)                  # $^{1}$
    txt = re.sub(r"\\textsuperscript\{[^{}]*\}", "", txt)
    txt = re.sub(r"\s{2,}", " ", txt).strip()
    return txt


def _plainify_affils(affils_tex: str) -> str:
    """Flatten ICCAS \\affils{...} into a single paragraph suitable for
    IJCAS' \\makeAuthorInformation{...} block."""
    txt = re.sub(r"\\\\", "; ", affils_tex)
    txt = re.sub(r"\$\{?\}?\^\{[^{}]*\}\$", "", txt)
    txt = re.sub(r"\$\^\{[^{}]*\}\$", "", txt)
    txt = re.sub(r"\{\\small\s*([^}]*)\}", r"\1", txt)
    # ``\\`` in ICCAS marks a line break, often preceded by ``,`` for the
    # multi-line affil. Flatten those into a single ``;`` so the IJCAS
    # one-paragraph layout doesn't end up with stray ``, ;`` punctuation.
    txt = re.sub(r",\s*;", ";", txt)
    txt = re.sub(r"\s+;\s+", "; ", txt)
    txt = re.sub(r";\s*;", ";", txt)
    txt = re.sub(r"\s{2,}", " ", txt).strip()
    return txt


def emit_ijcas(variant: str, run_id: str, entries: list[dict],
               dry_run: bool) -> None:
    print(f"[IJCAS] variant={variant}, run-id={run_id}")
    meta = _read_metadata()
    abstract = _read_clean_abstract(variant)
    year = time.strftime("%Y")

    # 1. title_abstract.tex (env form)
    ta = _IJCAS_TITLE_ABSTRACT_TMPL
    ta = ta.replace("__TITLE__",         meta["title"])
    ta = ta.replace("__AUTHORS_PLAIN__", _plainify_authors(meta["authors"]))
    ta = ta.replace("__AFFILS_PLAIN__",  _plainify_affils(meta["affils"]))
    ta = ta.replace("__ABSTRACT__",      abstract)
    ta = ta.replace("__KEYWORDS__",      meta["keywords"])
    ta = ta.replace("__YEAR__",          year)
    _write(os.path.join(_IJCAS_DIR, "tex", "title_abstract.tex"), ta, dry_run)
    print(f"  ✓ IJCAS/tex/title_abstract.tex written ({len(abstract)} char abstract)")

    # 2. Copy section files with figure-path rewriting (figs/).
    section_files = [
        "intro_related.tex",
        "method.tex",
        "experiment.tex",
        "conclusion.tex",
        "acknowledgement.tex",
        "biography.tex",
    ]
    for fn in section_files:
        src = os.path.join(_PAPER_DIR, "tex", fn)
        dst = os.path.join(_IJCAS_DIR, "tex", fn)
        _copy_with_rewrite(src, dst, dry_run, fig_dir="figs")

    # 3. main.tex — filter bibliography to only refs actually cited in
    #    the IJCAS body sources. The full survey lives unmodified in
    #    paper/literature_survey.md for context.
    cited = _cited_keys_in(*(
        os.path.join(_PAPER_DIR, "tex", fn)
        for fn in ("intro_related.tex", "method.tex", "experiment.tex",
                   "conclusion.tex", "acknowledgement.tex")
    ))
    ijcas_entries = [e for e in entries if e["key"] in cited] if cited else entries
    print(f"  → bibliography filtered: {len(ijcas_entries)}/{len(entries)} cited")
    bib_block = _bibliography_block(ijcas_entries) if ijcas_entries else \
                r"\begin{thebibliography}{99}" "\n" \
                "% no entries — populate paper/literature_survey.md\n" \
                r"\end{thebibliography}" "\n"
    main = _IJCAS_MAIN_TMPL.replace("__BIBLIOGRAPHY__", bib_block.rstrip())
    main = main.replace("__YEAR__", year)
    _write(os.path.join(_IJCAS_DIR, "main.tex"), main, dry_run)
    print(f"  ✓ IJCAS/main.tex written ({len(ijcas_entries)} bib entries)")

    # 4. references.bib
    generate_references_bib(_IJCAS_DIR, ijcas_entries, dry_run)

    # 5. figures (figs/), tables (tables/), portraits (portraits/)
    _link_figures_dir(run_id, os.path.join(_IJCAS_DIR, "figs"), dry_run)
    _link_tables_dir(os.path.join(_IJCAS_DIR, "tables"), dry_run)
    _link_portraits_dir(os.path.join(_IJCAS_DIR, "portraits"), dry_run)


# ─────────────────────────────────────────────────────────────────────
# Target=paper — preserve old top-level flow
# ─────────────────────────────────────────────────────────────────────
def emit_paper(variant: str, run_id: str, entries: list[dict],
               dry_run: bool) -> None:
    print(f"[paper] variant={variant}, run-id={run_id}")
    print("[1/6] title_abstract.tex")
    update_title_abstract(variant, dry_run)
    print()
    print("[2/6] experiment.tex")
    update_experiment_tex(dry_run)
    print()
    print("[3/6] references.bib")
    generate_references_bib(_PAPER_DIR, entries, dry_run)
    print()
    print("[4/6] main.tex bibliography block")
    if entries:
        update_main_bibliography(entries, dry_run)
    else:
        print("  [skip] no entries — main.tex bibliography untouched")
    print()
    print("[5/6] paper/figures/")
    setup_figures(run_id, dry_run)
    print()
    print("[6/6] paper/tables/")
    setup_tables(dry_run)


# ─────────────────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────────────────
def main() -> int:
    p = argparse.ArgumentParser(
        description="Refresh paper/ICCAS/IJCAS artifacts from paper/ sources.")
    p.add_argument("--target",
                   choices=["paper", "iccas", "ijcas", "both"],
                   default="paper",
                   help="Which output folder(s) to emit. "
                        "'both' = iccas+ijcas (typical pre-submission).")
    p.add_argument("--variant",
                   choices=["completeness", "verifier", "llama"],
                   default="completeness",
                   help="Which abstract variant to use.")
    p.add_argument("--run-id", default="latest",
                   help="figures/<run-id>/ to source .pdf/.eps from")
    p.add_argument("--dry-run", action="store_true")
    args = p.parse_args()

    print("init_paper")
    print(f"  target    : {args.target}")
    print(f"  variant   : {args.variant}")
    print(f"  run-id    : {args.run_id}")
    print(f"  dry-run   : {args.dry_run}")
    print()

    # Parse the survey once — all targets share the entry list.
    entries = _entries_from_survey()
    if not entries:
        print("  [warn] no entries parsed from paper/literature_survey.md")

    if args.target == "paper":
        emit_paper(args.variant, args.run_id, entries, args.dry_run)
    elif args.target == "iccas":
        emit_iccas(args.variant, args.run_id, entries, args.dry_run)
    elif args.target == "ijcas":
        emit_ijcas(args.variant, args.run_id, entries, args.dry_run)
    elif args.target == "both":
        emit_iccas(args.variant, args.run_id, entries, args.dry_run)
        print()
        emit_ijcas(args.variant, args.run_id, entries, args.dry_run)

    print()
    print("done.")
    if not args.dry_run and not shutil.which("pdflatex"):
        print()
        print("note: pdflatex not on PATH — cannot test-compile here.")
        if args.target in ("iccas", "both"):
            print("  cd ICCAS && pdflatex main.tex")
        if args.target in ("ijcas", "both"):
            print("  cd IJCAS && pdflatex main.tex")
        if args.target == "paper":
            print("  cd paper && pdflatex main.tex")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
